### PR TITLE
Added corestore.destroy

### PR DESCRIPTION
**Pull request by RangerMauve**
This builds off of the new [hypercore.destroy](https://github.com/mafintosh/hypercore/pull/250) method and adds `corestore.destroy` and `subcorestore.destroy`

These methods close the store, and then destroy the data for all the hypercores within it.

This will be useful for a `hyperdrive.destroy` so we can delete data for hyperdrives that we no longer whish to store on disk. Primary use case for me is for `dat-store`, but it will probably be useful for the daemon and any other application that might want to delete data.

One thing that I'm unsure about is whether to destroy the master key. What do you think about having a flag in `destroy` for this?

Also it looks like `standard --fix` may have updated some `let` statements to be `const`. I can revert that if you need.

Also also, I added an `npm run fix` command to fix linter errors in case people have a different version of standard installed on their machine (faced this with hypercore development). Lemme know if that should be removed too.

Gonna start working on `hyperdrive.destroy` in the meantime.

### CODE REVIEW

**Comment by andrewosh** [comment]
Hey @RangerMauve thanks for doing this! As my disk usage grows larger and larger every day, I too have been thinking about deletion...

A few things we should consider for this:
1. This will only destroy cores that are currently in memory, as it iterates over our in-memory maps and calls `destroy` on each. This might be fine behavior, but I don't think it will work for `internalCores`, because those cores have been passively requested by remote peers during discovery, and have not been actively loaded by the corestore user. Given that, you can never really be certain which cores will be destroyed if your corestore is replicating with anybody. Maybe this method should fail if there's an active replication stream (`this._replicationStreams` isn't empty)?
2. I'm a bit concerned that `destroy` and `close` are semantically too similar, at least in the stack currently. hyperswarm for example exposes a `destroy` method for "destroying" the swarm, but this is not a high-risk operation. Given that `corestore.destroy` leads to data loss, I feel like we should make it extremely clear what the operation is doing -- this might be solvable just in the docs.

Building off (1) a bit, we might want to require that `destroy` takes a list of keys that should be deleted, and require that a `force` or `deleteAll` flag is explicitly set to true in order to proceed with a full deletion. This would decouple the list of keys you want to delete from the current state of the corestore's memory, which sounds more user-friendly to me and less likely to lead to unexpected results.

Lemme know what you think about these. We definitely want this, but especially since we're working with a model where we have tons of `NamespacedCorestores` building off of a single storage location, we need to be really careful about not blasting everything away! No code nits though -- once we work out these issues I'll merge.

__Edit__: `internalCores` contains both cores that have been requested through `get`, and those that have been passively requested during replication. If a core is external cores, then we can never garbage collect it until it's manually closed, but if it's in `internalCores` only, then we can auto-GC them, hence why that cache is an LRU. The caching is kinda confusing (and has given us, and I think you, pain in the past).

**Comment by RangerMauve** [comment]
Regarding the naming of `destroy`, I was basing it on the language in [random-access-storage](https://github.com/random-access-storage/random-access-storage#storagedestroycallback) where it destroys the underlying data whereas `close` clears any file descriptors and stuff from memory.

Would something like `destroyData` be better? Personally I think the docs could be clear enough. Maybe we should have some bold text saying **THIS WILL DELETE YOUR DATA** to get the point across.

I was kinda grasping for straws when I was looking at what cores to destroy in the main corestore. For namespaced corestores, I think it's pretty straightforward, though.

I love the idea of passing in a list of keys to destroy with an optional flag to destroy all of them! I'm down to add that change if you're still up for it.

**Comment by m4gpi** [comment]
Hope you guys don't mind me wading in, we're looking at destroy functionality at the moment in kappa-drive and cobox. It probably makes sense for this function to be named `destroyAll` rather than `destroy`, where instead a destroy function takes a key and deletes _just a single hypercore_, rather than all cores. 

```
destroy (key) {
  // destroy just a single hypercore
}

destroyAll () {
  // destroy all cores
}
```

I think this is much clearer and safer. It may reduce a possible accident where all hypercores were destroyed, instead of just one, which would suck. We're using a single corestore across multiple multifeed instances (that said, with a namespace, so its unlikely this would happen... but...), so if we were to accidentally delete data from the wrong multifeed, folks would not be happy.

Regarding the naming, I think general convention with destroy is that it does purge and  remove data. So I'd assume that this does exactly that - whereas close I don't think implies the data is to be deleted, merely that its safely exiting the program.

And regarding the master key, we're using our own, which corestore actually doesn't know about except as an option, so it makes sense that either it'd ignore that, or only delete if it was generated by corestore itself.

Hope thats helpful!

**Comment by RangerMauve** [comment]
Lately, I've been thinking that corestore isn't the best place to destroy cores from. I've been calling the `destroyData` method on the hypercore itself when I want to destroy it, or on the set of hypercores that I want destroyed one by one. :O

**Comment by andrewosh** [comment]
Yeah I'm with @RangerMauve on this one, at least until we have a really front-and-center way of doing key backups. Until that's solved, doing it manually on a per-core basis is probably the best way to go. It's tedious, but at least it's explicit about exactly what's being deleted.

Once we have backup/restore in place, then perhaps a `destroy` method in Corestore can automatically do the backup before doing the deletion, just to be extra safe.

**Comment by RangerMauve** [comment]
An example of where hypercore destruction is already being used is in Hyperdrive's [destroyStorage](https://github.com/hypercore-protocol/hyperdrive/blob/master/index.js#L844) method. Not sure if that's relevant.

**Comment by mafintosh** [comment]
Still relevant but PR is old and incompat with 6, so closing for now

**Pull request closed without merging**
